version: "2"
services:
  ssh-client:
    hostname: 'ssh-client'
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    entrypoint: /bin/bash 
    stdin_open: true # docker run -i
    tty: true        # docker run -t
